<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>brisk-app</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BriskEngine\BriskEngine.csproj" />
    <ProjectReference Include="..\Brisk.Cli\Brisk.Cli.csproj" />
  </ItemGroup>
</Project>
